image: "python:3.7"

before_script:
  - python --version
  - pip install pipenv
  - pipenv install 
  - pipenv install requests

stages:
  - Test

unittest:
  stage: Test
  script:
  - python -m unittest discover